import jsPDF from 'jspdf';

function formatDate() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
}

function addPageChrome(doc, pageNum, total) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  // Top blue ribbon
  doc.setFillColor(34, 81, 255);
  doc.rect(0, 0, pw, 3, 'F');

  // Header text
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180);
  doc.text('BizLens — Confidential Strategic Report', 14, 9);
  doc.text(`${pageNum} / ${total}`, pw - 14, 9, { align: 'right' });

  // Bottom line
  doc.setDrawColor(220);
  doc.setLineWidth(0.3);
  doc.line(14, ph - 8, pw - 14, ph - 8);
  doc.setFontSize(7);
  doc.text('Generated by BizLens AI Platform', 14, ph - 4);
  doc.text(new Date().toLocaleDateString(), pw - 14, ph - 4, { align: 'right' });

  doc.setTextColor(0);
}

function sectionTitle(doc, text, y) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(34, 81, 255);
  doc.text(text.toUpperCase(), 14, y);
  doc.setDrawColor(34, 81, 255);
  doc.setLineWidth(0.5);
  doc.line(14, y + 1.5, 14 + doc.getTextWidth(text.toUpperCase()), y + 1.5);
  doc.setTextColor(0);
  doc.setDrawColor(220);
  return y + 8;
}

function bodyText(doc, text, x, y, maxWidth) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(60);
  const lines = doc.splitTextToSize(text || '', maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * 4.5;
}

export default function ExportButton({ analysisResult, dataProfile, sector }) {
  const handleExport = () => {
    if (!analysisResult) return;

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    const margin = 14;
    const cw = pw - margin * 2;
    const TOTAL_PAGES = 4;

    // ─── PAGE 1: Cover ───────────────────────────────────────────────────
    doc.setFillColor(34, 81, 255);
    doc.rect(0, 0, pw, 3, 'F');

    // Cover hero block
    doc.setFillColor(245, 245, 245);
    doc.rect(0, 3, pw, 70, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(10, 10, 10);
    doc.text('BizLens', margin, 30);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(80);
    doc.text('AI Strategic Analysis Report', margin, 40);

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(`Sector: ${sector || 'General Business'}`, margin, 50);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, 57);
    doc.text(`Confidential — For Internal Use Only`, margin, 64);

    // Thin separator
    doc.setDrawColor(200);
    doc.setLineWidth(0.3);
    doc.line(margin, 75, pw - margin, 75);

    // Problem statement
    let y = 84;
    y = sectionTitle(doc, 'Problem Statement', y);
    y = bodyText(doc, analysisResult.problemStatement, margin, y, cw);

    // Executive summary
    y += 8;
    y = sectionTitle(doc, 'Executive Summary', y);
    y = bodyText(doc, analysisResult.executiveSummary, margin, y, cw);

    // Dataset stats if available
    if (dataProfile) {
      y += 8;
      y = sectionTitle(doc, 'Dataset Overview', y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(60);
      doc.text([
        `Rows: ${dataProfile.rowCount?.toLocaleString() || '—'}`,
        `Columns: ${dataProfile.columnCount || '—'}`,
        `Anomalies detected: ${dataProfile.anomalies?.length || 0}`,
        `Date columns: ${dataProfile.dateColumns?.length || 0}`,
      ], margin, y, { lineHeightFactor: 1.6 });
    }

    addPageChrome(doc, 1, TOTAL_PAGES);

    // ─── PAGE 2: KPIs ────────────────────────────────────────────────────
    doc.addPage();
    addPageChrome(doc, 2, TOTAL_PAGES);

    y = 18;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(10);
    doc.text('Key Performance Indicators', margin, y);
    y += 10;

    const STATUS_RGB = { good: [16, 185, 129], warning: [245, 158, 11], critical: [239, 68, 68] };
    const kpis = analysisResult.kpis || [];
    const colW = cw / 2;

    kpis.forEach((kpi, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = margin + col * (colW + 2);
      const cardY = y + row * 38;

      if (cardY > ph - 30) return;

      const rgb = STATUS_RGB[kpi.status] || STATUS_RGB.warning;
      doc.setFillColor(...rgb);
      doc.rect(x, cardY, 3, 30, 'F');

      doc.setFillColor(250, 250, 250);
      doc.rect(x + 3, cardY, colW - 3, 30, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(40);
      doc.text(kpi.name, x + 6, cardY + 6);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(10);
      doc.text(String(kpi.value), x + 6, cardY + 15);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(120);
      doc.text(`Benchmark: ${kpi.benchmark || 'N/A'}   Delta: ${kpi.delta || '—'}`, x + 6, cardY + 22);

      doc.setFontSize(7);
      doc.setTextColor(...rgb);
      doc.setFont('helvetica', 'bold');
      doc.text((kpi.status || '').toUpperCase(), x + 6, cardY + 28);
    });

    // ─── PAGE 3: Issue Tree ───────────────────────────────────────────────
    doc.addPage();
    addPageChrome(doc, 3, TOTAL_PAGES);

    y = 18;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(10);
    doc.text('Issue Tree Analysis', margin, y);
    y += 8;

    const tree = analysisResult.issueTree;
    if (tree) {
      doc.setFillColor(20, 20, 20);
      doc.rect(margin, y, cw, 12, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255);
      const rootLines = doc.splitTextToSize(`ROOT: ${tree.root}`, cw - 6);
      doc.text(rootLines, margin + 3, y + 5);
      doc.setTextColor(0);
      y += 16;

      const SEV_RGB = { high: [239, 68, 68], medium: [245, 158, 11], low: [34, 81, 255] };

      (tree.branches || []).forEach((branch, bi) => {
        if (y > ph - 20) return;
        const rgb = SEV_RGB[branch.severity] || SEV_RGB.medium;

        doc.setFillColor(248, 248, 248);
        doc.rect(margin, y, cw, 8, 'F');
        doc.setFillColor(...rgb);
        doc.rect(margin, y, 2.5, 8, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(10);
        doc.text(`${bi + 1}. ${branch.label}`, margin + 5, y + 5.5);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(...rgb);
        doc.text((branch.severity || '').toUpperCase(), pw - margin - 3, y + 5.5, { align: 'right' });

        y += 11;
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(80);
        const descLines = doc.splitTextToSize(branch.description, cw - 8);
        doc.text(descLines, margin + 5, y);
        y += descLines.length * 4.2 + 2;

        (branch.leaves || []).forEach((leaf) => {
          if (y > ph - 20) return;
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(60);
          const leafLines = doc.splitTextToSize(`→  ${leaf}`, cw - 14);
          doc.text(leafLines, margin + 10, y);
          y += leafLines.length * 4 + 1.5;
        });
        y += 5;
      });
    }

    // ─── PAGE 4: Recommendations ──────────────────────────────────────────
    doc.addPage();
    addPageChrome(doc, 4, TOTAL_PAGES);

    y = 18;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(10);
    doc.text('Strategic Recommendations — SCR Format', margin, y);
    y += 8;

    const IMPACT_RGB = { high: [239, 68, 68], medium: [245, 158, 11], low: [34, 81, 255] };
    const recs = (analysisResult.recommendations || []).slice(0, 4);

    recs.forEach((rec, ri) => {
      if (y > ph - 30) return;

      const rgb = IMPACT_RGB[rec.impact] || IMPACT_RGB.medium;

      doc.setFillColor(245, 245, 245);
      doc.rect(margin, y, cw, 10, 'F');
      doc.setFillColor(...rgb);
      doc.rect(margin, y, 3, 10, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(10);
      doc.text(`R${ri + 1}: ${rec.title}`, margin + 6, y + 7);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...rgb);
      doc.text(`${(rec.impact || '').toUpperCase()} IMPACT`, pw - margin - 2, y + 7, { align: 'right' });
      y += 14;

      [
        { label: 'Situation', key: 'situation', tc: [30, 100, 200] },
        { label: 'Complication', key: 'complication', tc: [180, 100, 20] },
        { label: 'Resolution', key: 'resolution', tc: [20, 140, 80] },
      ].forEach(({ label, key, tc }) => {
        if (y > ph - 15) return;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(...tc);
        doc.text(`${label.toUpperCase()}:`, margin + 2, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60);
        const vLines = doc.splitTextToSize(rec[key] || '', cw - 30);
        doc.text(vLines, margin + 28, y);
        y += vLines.length * 4.2 + 2;
      });

      if (rec.metric) {
        doc.setFillColor(10, 10, 10);
        doc.rect(margin, y, cw, 7, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(255);
        doc.text(`Expected Outcome: ${rec.metric}`, margin + 4, y + 4.5);
        doc.setTextColor(0);
        y += 10;
      }
      y += 7;
    });

    doc.save(`BizLens_Report_${formatDate()}.pdf`);
  };

  return (
    <button
      onClick={handleExport}
      disabled={!analysisResult}
      className="flex items-center gap-2 px-4 py-2.5 bg-gray-900 text-white text-[12px] font-bold uppercase tracking-wider hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Export PDF
    </button>
  );
}
